import type { Metadata } from "next";
// import localFont from "next/font/local";
import { ReactQueryProvider } from "@/providers/react-query-provider";

// import Header from "@/components/layout/header";
// import Footer from "@/components/layout/footer";

import "./globals.css";
import "driver.js/dist/driver.css";

// const leagueSpartanSans = localFont({
//   src: "./fonts/LeagueSpartan-VariableFont_wght.ttf",
//   variable: "--font-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Ezfiles AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
